name: NuGet Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Clone Actions Repo
      shell: bash
      run: |
        git clone https://${{ secrets.GithubPackages_Key }}@github.com/mou-haz/GitHub-WorkFlows

    - name: Publish MinimalSoft.MinimalMediator.Abstractions
      uses: "./GitHub-WorkFlows/.github/steps/package_publish"
      with:
        token: ${{ secrets.GITHUBPACKAGES_KEY }}
        repo_name: "MinimalMediator"
        pkg_name: "MinimalSoft.MinimalMediator.Abstractions","MinimalSoft.MinimalMediator"
        nuget_token: ${{ secrets.Nu_Key }}
        github_packages_token: ${{ secrets.GITHUBPACKAGES_KEY }}